name: Copy Resume to Personal Website

on:
  push:
    branches: [ main ]

jobs:
  copy-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Copy the PDF file
      run: cp -f ./build/resume.pdf ./yvesyil.github.io/curriculum-vitae.pdf

    - name: Commit and push changes
      run: |
        cd ./yvesyil.github.io
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Copy PDF file"
        git push origin main